version: '3'

services:

  db:
    image: neo4j:latest
    env_file:
      - '.env'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - 'db:/data'
  web:
    build: '.'
    command: "tail -f /dev/null"
    depends_on:
      - 'db'
    env_file:
      - '.env'
    ports: 
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - 'db:db'

volumes:
  db:
